///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderPickItem {
/*
{
  "name": "联系不上顾客",
  "code": "10001"
}
*/

  String? name;
  String? code;

  OrderPickItem({
    this.name,
    this.code,
  });
  OrderPickItem.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['code'] = code;
    return data;
  }
}

class OrderErrorEntity {
/*
{
  "name": "顾客异常",
  "code": "1",
  "children": [
    {
      "name": "联系不上顾客",
      "code": "10001"
    }
  ]
}
*/

  String? name;
  String? code;
  List<OrderPickItem?>? children;

  OrderErrorEntity({
    this.name,
    this.code,
    this.children,
  });
  OrderErrorEntity.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    code = json['code']?.toString();
  if (json['children'] != null) {
  final v = json['children'];
  final arr0 = <OrderPickItem>[];
  v.forEach((v) {
  arr0.add(OrderPickItem.fromJson(v));
  });
    children = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['code'] = code;
    if (children != null) {
      final v = children;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['children'] = arr0;
    }
    return data;
  }
}
