name: djqs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 5.1.2+512

environment:
  sdk: '>=3.4.4 <4.0.0'

#tobias:
#  url_scheme: alipay
#
#fluwx:
#  app_id: 'wx5f9f26d36c878d20'
#  #  debug_logging: false
#  #  android:
#  #      interrupt_wx_request: true
#  #      flutter_activity: 'MainActivity' # Defaults to app's launcher
#  ios:
#    universal_link: https://dj-common.kuaimasupin.com
#    # scene_delegate: true # Defaults to false.
#    no_pay: false # Set to false to disable payment.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #popular most >2500
  #get: ^4.6.5
  provider: ^6.0.0
  shared_preferences: ^2.0.12
  #http: ^ 1.1.0
  url_launcher: ^6.2.2 #邮件电话短信网址文件地址
  flutter_native_splash: ^2.3.8
  dio: ^5.3.3
  image_picker: ^1.0.1 #图片选择,拍照/文件
  cached_network_image: ^3.3.0
  #animations: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^15.1.1
  #google_fonts: ^5.1.0
  #geolocator: ^9.0.2 #定位权限和坐标获取
  intl: ^0.19.0
  #flutter_spinkit: ^5.0.0 #loading动画
  permission_handler: ^11.3.1
  #carousel_slider: ^4.2.1 #轮播图
  flutter_svg: ^2.0.7  #加载svg
  path_provider: ^2.1.2
  #font_awesome_flutter: ^10.5.0 #免费图标库
  flutter_screenutil: ^5.9.0
  #file_picker: ^5.2.7 #文件选择
  #go_router: ^10.0.0 #路由管理
  webview_flutter: ^4.4.2
  audioplayers: ^5.2.0
  #get_it: ^7.2.0
  device_preview: ^1.2.0 #ui适配检测
  #  flutter_staggered_grid_view: 0.7.0 #瀑布流
  fluttertoast: ^8.2.1
  #flutter_secure_storage: ^8.0.0 #敏感数据存储(keychina和aes加密)
  logger: ^2.0.1
  #pinput: ^5.0.0 #短信自动填充含ui googleplay和firebase
  #flex_color_scheme: ^7.3.1 #主题配色

  #popular more>1500
  #  badges: ^3.1.0 #角标红点
  connectivity_plus: ^5.0.2
  #  video_player: ^2.8.1
  photo_view: ^0.14.0 #图片预览
  camera: ^0.10.5
  flutter_easyloading: ^3.0.5 #loading动画,基于flutter_spinkit
  device_info_plus: ^8.2.2
  package_info_plus: ^6.0.0
  upgrader: ^10.0.0
  #pull_to_refresh: ^2.0.0 #out
  #dropdown_button2: ^2.3.8
  dotted_border: ^2.0.0
  #image: ^4.5.4
  syncfusion_flutter_datepicker: ^24.1.46

  #popular >1000
  uni_links: ^0.5.1
  flutter_cache_manager: ^3.3.1 #文件等数据缓存
  crypto: ^3.0.1 #md5 sha加密
  #flutter_tts: ^3.6.3
  screenshot: ^ 3.0.0 #截屏生成图片
  flutter_image_compress: ^ 2.1.0
  app_settings: ^6.1.1

  #UI及效果相关
  #shimmer: ^3.0.0
  #animated_text_kit: ^4.2.2
  #animations: ^2.0.7
  flutter_app_badger: ^1.5.0
  extended_sliver: ^2.1.3

  #视频相关
  #video_compress: ^3.1.2
  #video_thumbnail: ^0.5.3
  #ffmpeg_kit_flutter: ^5.1.0
  volume_controller: ^ 3.3.3

  #图片相关
  image_gallery_saver: ^2.0.1 #保存至相册
  #reorderables: ^0.6.0

  #音频相关
  #audio_session: 0.1.7

  #其他
  json_annotation: ^4.8.0
  web_socket_channel: ^2.2.0 #socket连接
  ota_update: ^5.1.0 #检查更新
  map_launcher: ^3.4.0 #地图list
  #mobile_number: ^2.1.1
  encrypt: ^5.0.3
  telephony: ^0.2.0
  flutter_picker: ^2.1.0
  lpinyin: ^2.0.3
  extended_text_field: ^15.0.0

  #三方sdk
  umeng_common_sdk: ^1.2.7
  jpush_flutter: ^3.2.8
  #  fluwx: ^4.4.3 #微信支付和分享
  amap_flutter_base: ^3.0.0
  amap_flutter_map: ^3.0.0
  amap_flutter_location: ^3.0.0
  #  tobias: ^3.1.2 #支付宝支付
#  tencent_cloud_chat_sdk: ^6.1.13
  tencent_cloud_chat_sdk: ^8.5.6864+4
#  tencentcloud_cos_sdk_plugin: ^1.2.4
  tencentcloud_cos_sdk_plugin: ^1.2.1
  tencent_map_flutter:
    path: plugins/tencent_map_flutter-main/
#  vod_upload_flutter:
#    path: plugins/vod_upload/

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
#dependency_overrides:
#  platform: ^3.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: baseIF
      fonts:
        - asset: res/images/base_iconfont.ttf
    - family: sansbold
      fonts:
        - asset: assets/fonts/sans_bold.otf

  assets:
    - res/emoji/
    - assets/images/
    - assets/data/index.json
    - assets/data/emoji_list.json
    - assets/sound/
    #- google_fonts/

#flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
