///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PushTransEntityExtrasData {
/*
{
  "order_type": "outrider",
  "notice_type": "outrider_new_order"
}
*/

  String? orderType;
  String? noticeType;
  String? orderId;
  int? listType;

  PushTransEntityExtrasData({this.orderType, this.noticeType, this.orderId,this.listType});

  PushTransEntityExtrasData.fromJson(Map<String, dynamic> json) {
    orderType = json['order_type']?.toString();
    noticeType = json['notice_type']?.toString();
    orderId = json['order_id']?.toString();
    orderId = json['list_type']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['order_type'] = orderType;
    data['notice_type'] = noticeType;
    data['order_id'] = orderId;
    data['list_type'] = orderId;

    return data;
  }
}

class PushTransEntityExtras {
/*
{
  "content": "你有个新订单 请注意查收",
  "data": {
    "order_type": "outrider",
    "notice_type": "outrider_new_order"
  }
}
*/

  String? content;
  PushTransEntityExtrasData? data;

  PushTransEntityExtras({
    this.content,
    this.data,
  });

  PushTransEntityExtras.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
    data = (json['data'] != null)
        ? PushTransEntityExtrasData.fromJson(json['data'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class PushTransEntity {
/*
{
  "user_id": "22",
  "title": "张彦强测试333",
  "extras": {
    "content": "你有个新订单 请注意查收",
    "data": {
      "order_type": "outrider",
      "notice_type": "outrider_new_order"
    }
  }
}
*/

  String? userId;
  String? title;
  PushTransEntityExtras? extras;

  PushTransEntity({
    this.userId,
    this.title,
    this.extras,
  });

  PushTransEntity.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
    title = json['title']?.toString();
    extras = (json['extras'] != null)
        ? PushTransEntityExtras.fromJson(json['extras'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['title'] = title;
    if (extras != null) {
      data['extras'] = extras!.toJson();
    }
    return data;
  }
}
