///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MapRouteEntityResultRoutesSteps {
/*
{
  "instruction": "从起点朝南,行进175米,偏右转",
  "polyline_idx": [
    0
  ],
  "road_name": "",
  "dir_desc": "南",
  "distance": 175,
  "act_desc": "偏右转",
  "road_class": 100
}
*/

  String? instruction;
  List<int?>? polylineIdx;
  String? roadName;
  String? dirDesc;
  int? distance;
  String? actDesc;
  int? roadClass;

  MapRouteEntityResultRoutesSteps({
    this.instruction,
    this.polylineIdx,
    this.roadName,
    this.dirDesc,
    this.distance,
    this.actDesc,
    this.roadClass,
  });
  MapRouteEntityResultRoutesSteps.fromJson(Map<String, dynamic> json) {
    instruction = json['instruction']?.toString();
    if (json['polyline_idx'] != null) {
      final v = json['polyline_idx'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      polylineIdx = arr0;
    }
    roadName = json['road_name']?.toString();
    dirDesc = json['dir_desc']?.toString();
    distance = json['distance']?.toInt();
    actDesc = json['act_desc']?.toString();
    roadClass = json['road_class']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['instruction'] = instruction;
    if (polylineIdx != null) {
      final v = polylineIdx;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['polyline_idx'] = arr0;
    }
    data['road_name'] = roadName;
    data['dir_desc'] = dirDesc;
    data['distance'] = distance;
    data['act_desc'] = actDesc;
    data['road_class'] = roadClass;
    return data;
  }
}

class MapRouteEntityResultRoutes {
/*
{
  "mode": "EBICYCLING",
  "distance": 5614,
  "duration": 22,
  "direction": "南",
  "polyline": [
    39.818926
  ],
  "steps": [
    {
      "instruction": "从起点朝南,行进175米,偏右转",
      "polyline_idx": [
        0
      ],
      "road_name": "",
      "dir_desc": "南",
      "distance": 175,
      "act_desc": "偏右转",
      "road_class": 100
    }
  ]
}
*/

  String? mode;
  int? distance;
  int? duration;
  String? direction;
  List<double?>? polyline;
  List<MapRouteEntityResultRoutesSteps?>? steps;

  MapRouteEntityResultRoutes({
    this.mode,
    this.distance,
    this.duration,
    this.direction,
    this.polyline,
    this.steps,
  });
  MapRouteEntityResultRoutes.fromJson(Map<String, dynamic> json) {
    mode = json['mode']?.toString();
    distance = json['distance']?.toInt();
    duration = json['duration']?.toInt();
    direction = json['direction']?.toString();
    if (json['polyline'] != null) {
      final v = json['polyline'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      polyline = arr0;
    }
    if (json['steps'] != null) {
      final v = json['steps'];
      final arr0 = <MapRouteEntityResultRoutesSteps>[];
      v.forEach((v) {
        arr0.add(MapRouteEntityResultRoutesSteps.fromJson(v));
      });
      steps = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mode'] = mode;
    data['distance'] = distance;
    data['duration'] = duration;
    data['direction'] = direction;
    if (polyline != null) {
      final v = polyline;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['polyline'] = arr0;
    }
    if (steps != null) {
      final v = steps;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['steps'] = arr0;
    }
    return data;
  }
}

class MapRouteEntityResult {
/*
{
  "routes": [
    {
      "mode": "EBICYCLING",
      "distance": 5614,
      "duration": 22,
      "direction": "南",
      "polyline": [
        39.818926
      ],
      "steps": [
        {
          "instruction": "从起点朝南,行进175米,偏右转",
          "polyline_idx": [
            0
          ],
          "road_name": "",
          "dir_desc": "南",
          "distance": 175,
          "act_desc": "偏右转",
          "road_class": 100
        }
      ]
    }
  ]
}
*/

  List<MapRouteEntityResultRoutes?>? routes;

  MapRouteEntityResult({
    this.routes,
  });
  MapRouteEntityResult.fromJson(Map<String, dynamic> json) {
    if (json['routes'] != null) {
      final v = json['routes'];
      final arr0 = <MapRouteEntityResultRoutes>[];
      v.forEach((v) {
        arr0.add(MapRouteEntityResultRoutes.fromJson(v));
      });
      routes = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (routes != null) {
      final v = routes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['routes'] = arr0;
    }
    return data;
  }
}

class MapRouteEntity {
/*
{
  "status": 0,
  "message": "Success",
  "request_id": "8f2ee49b61974765bfc6c4fe23552773",
  "result": {
    "routes": [
      {
        "mode": "EBICYCLING",
        "distance": 5614,
        "duration": 22,
        "direction": "南",
        "polyline": [
          39.818926
        ],
        "steps": [
          {
            "instruction": "从起点朝南,行进175米,偏右转",
            "polyline_idx": [
              0
            ],
            "road_name": "",
            "dir_desc": "南",
            "distance": 175,
            "act_desc": "偏右转",
            "road_class": 100
          }
        ]
      }
    ]
  }
}
*/

  int? status;
  String? message;
  String? requestId;
  MapRouteEntityResult? result;

  MapRouteEntity({
    this.status,
    this.message,
    this.requestId,
    this.result,
  });
  MapRouteEntity.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    requestId = json['request_id']?.toString();
    result = (json['result'] != null) ? MapRouteEntityResult.fromJson(json['result']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['request_id'] = requestId;
    if (result != null) {
      data['result'] = result!.toJson();
    }
    return data;
  }
}
