///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BillListEntityDateKeyList {
/*
{
  "label": "当期",
  "value": ""
}
*/

  String? label;
  String? value;

  BillListEntityDateKeyList({
    this.label,
    this.value,
  });

  BillListEntityDateKeyList.fromJson(Map<String, dynamic> json) {
    label = json['label']?.toString();
    value = json['value']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['label'] = label;
    data['value'] = value;
    return data;
  }
}

class BillListEntity {
/*
{
  "date_key_list": [
    {
      "label": "当期",
      "value": ""
    }
  ]
}
*/

  List<BillListEntityDateKeyList?>? dateKeyList;

  BillListEntity({
    this.dateKeyList,
  });

  BillListEntity.fromJson(Map<String, dynamic> json) {
    if (json['date_key_list'] != null) {
      final v = json['date_key_list'];
      final arr0 = <BillListEntityDateKeyList>[];
      v.forEach((v) {
        arr0.add(BillListEntityDateKeyList.fromJson(v));
      });
      dateKeyList = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dateKeyList != null) {
      final v = dateKeyList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['date_key_list'] = arr0;
    }
    return data;
  }
}
