///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckWithdrawlEntityNotice {
/*
{
  "header": "【账户安全风险提示】",
  "content": "尊敬的客户，系统检测到您当前用于提现的微信账号绑定手机号（尾号‌）与顺单侠账户预留手机号（尾号‌）不一致。为保障您的资金安全，请您注意：\n          1. 手机号不匹配可能导致资金风险,将提现至15010130525\n          2. 非本人操作请立即终止流程\n          3. 如有疑问请联系配送站点",
  "footer": "请确认本次操作是否本人发起："
}
*/

  String? header;
  String? content;
  String? footer;

  CheckWithdrawlEntityNotice({
    this.header,
    this.content,
    this.footer,
  });
  CheckWithdrawlEntityNotice.fromJson(Map<String, dynamic> json) {
    header = json['header']?.toString();
    content = json['content']?.toString();
    footer = json['footer']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['header'] = header;
    data['content'] = content;
    data['footer'] = footer;
    return data;
  }
}

class CheckWithdrawlEntityList {
/*
{
  "id": "14",
  "rider_uid": "2",
  "type": "wechat",
  "account": "o-cf16ycdYrbWmV4hhjaMn6MC2kM",
  "ext_json": "{\"mobile\":\"18524426188\",\"purePhoneNumber\":\"15010130525\",\"self_flag\":0}",
  "create_time": "2025-03-29 12:43:24",
  "update_time": "2025-03-29 12:43:24",
  "self_flag": 0
}
*/

  String? id;
  String? riderUid;
  String? type;
  String? account;
  String? extJson;
  String? createTime;
  String? updateTime;
  int? selfFlag;

  CheckWithdrawlEntityList({
    this.id,
    this.riderUid,
    this.type,
    this.account,
    this.extJson,
    this.createTime,
    this.updateTime,
    this.selfFlag,
  });
  CheckWithdrawlEntityList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    riderUid = json['rider_uid']?.toString();
    type = json['type']?.toString();
    account = json['account']?.toString();
    extJson = json['ext_json']?.toString();
    createTime = json['create_time']?.toString();
    updateTime = json['update_time']?.toString();
    selfFlag = json['self_flag']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['rider_uid'] = riderUid;
    data['type'] = type;
    data['account'] = account;
    data['ext_json'] = extJson;
    data['create_time'] = createTime;
    data['update_time'] = updateTime;
    data['self_flag'] = selfFlag;
    return data;
  }
}

class CheckWithdrawlEntity {
/*
{
  "list": [
    {
      "id": "14",
      "rider_uid": "2",
      "type": "wechat",
      "account": "o-cf16ycdYrbWmV4hhjaMn6MC2kM",
      "ext_json": "{\"mobile\":\"18524426188\",\"purePhoneNumber\":\"15010130525\",\"self_flag\":0}",
      "create_time": "2025-03-29 12:43:24",
      "update_time": "2025-03-29 12:43:24",
      "self_flag": 0
    }
  ],
  "notice": {
    "header": "【账户安全风险提示】",
    "content": "尊敬的客户，系统检测到您当前用于提现的微信账号绑定手机号（尾号‌）与顺单侠账户预留手机号（尾号‌）不一致。为保障您的资金安全，请您注意：\n          1. 手机号不匹配可能导致资金风险,将提现至15010130525\n          2. 非本人操作请立即终止流程\n          3. 如有疑问请联系配送站点",
    "footer": "请确认本次操作是否本人发起："
  }
}
*/

  List<CheckWithdrawlEntityList?>? list;
  CheckWithdrawlEntityNotice? notice;

  CheckWithdrawlEntity({
    this.list,
    this.notice,
  });
  CheckWithdrawlEntity.fromJson(Map<String, dynamic> json) {
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <CheckWithdrawlEntityList>[];
      v.forEach((v) {
        arr0.add(CheckWithdrawlEntityList.fromJson(v));
      });
      list = arr0;
    }
    notice = (json['notice'] != null) ? CheckWithdrawlEntityNotice.fromJson(json['notice']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (list != null) {
      final v = list;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['list'] = arr0;
    }
    if (notice != null) {
      data['notice'] = notice!.toJson();
    }
    return data;
  }
}
